stages:
  preprocess:
    cmd: python src/preprocess.py --train_csv 
      data/raw/customer_churn_dataset-training-master.csv --test_csv 
      data/raw/customer_churn_dataset-testing-master.csv --out_dir 
      data/processed --test_size 0.20 --val_size 0.20 --random_state 42
    deps:
    - data/raw/customer_churn_dataset-testing-master.csv
    - data/raw/customer_churn_dataset-training-master.csv
    - src/preprocess.py
    outs:
    - data/processed
